# Generated by Django 5.2.1 on 2025-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labels',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(error_messages={'unique': 'This label with this name already exists. Please choose another name.'}, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
