# Generated by Django 5.2.1 on 2025-11-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options_alter_labels_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labels',
            options={'verbose_name': 'Labels', 'verbose_name_plural': 'Labels'},
        ),
    ]
